# 1. Import the numpy package under the name np

In [1]:
import numpy as np

## 2. Create a null vector of size 10


In [2]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 3. Create a vector with values ranging from 10 to 49


In [3]:
arr1 = np.arange(10,49)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


## 4. Find the shape of previous array in question 3


In [4]:
np.shape(arr1)

(39,)

## 5. Print the type of the previous array in question 3


In [5]:
arr1.dtype

dtype('int32')

## 6. Print the numpy version and the configuration


In [6]:
np.__version__

'1.18.1'

In [7]:
np.__config__

<module 'numpy.__config__' from 'C:\\Users\\Salman\\anaconda3\\lib\\site-packages\\numpy\\__config__.py'>

## 7. Print the dimension of the array in question 3


In [8]:
arr1.ndim

1

## 8. Create a boolean array with all the True values


In [9]:
arr_bool = np.ones(10, dtype=bool)
print(arr_bool)

[ True  True  True  True  True  True  True  True  True  True]


## 9. Create a two dimensional array


In [10]:
arr2 = np.zeros([3,2])
print(arr2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
arr2.ndim

2

## 10. Create a three dimensional array


In [12]:
arr3 = x = np.ones((3,2,2))
print(arr3)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [13]:
arr3.ndim

3

## 11. Reverse a vector (first element becomes last)


In [14]:
arr4 = np.array([1,2,3,4,5,6])
print(arr4)

[1 2 3 4 5 6]


In [15]:
arr4 = arr4[::-1]
print(arr4)

[6 5 4 3 2 1]


## 12. Create a null vector of size 10 but the fifth value which is 1


In [16]:
arr5 = np.zeros([10])
arr5[5] = 1
print(arr5)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


## 13. Create a 3x3 identity matrix


In [17]:
arr6 = np.identity(3)
print(arr6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 14. arr = np.array([1, 2, 3, 4, 5])   Convert the data type of the given array from int to float

In [18]:
arr_int = np.array([1, 2, 3, 4, 5])
arr_int

array([1, 2, 3, 4, 5])

In [19]:
arr_float = np.asfarray(arr_int)
print(arr_float)

[1. 2. 3. 4. 5.]


## 15. 
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])


In [20]:
arr_x = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr_y = np.array([[0., 4., 1.],[7., 2., 12.]])

In [21]:
arr_r = arr_x *arr_y
print(arr_r)

[[ 0.  8.  3.]
 [28. 10. 72.]]


## 16. Make an array by comparing both the arrays provided above in numpy

In [22]:
np.concatenate((arr_x,arr_y))

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

## 17. Extract all odd numbers from arr with values(0-9)


In [23]:
arr7 = np.arange(0,10)
new_arr7 = arr7[arr7 % 2 == 1]
print(new_arr7)

[1 3 5 7 9]


## 18. Replace all odd numbers to -1 from previous array


In [24]:
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.where(arr7 % 2 != 0, -1,arr7 )

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 19.
arr = np.arange(10)

Replace the values of indexes 5,6,7 and 8 to 12

In [26]:
arr8 = np.arange(10)
arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
for i in arr8:
    if i>=5 and i<=8:
        arr8[i] = 12
print(arr8)

[ 0  1  2  3  4 12 12 12 12  9]


## 20. Create a 2d array with 1 on the border and 0 inside


In [28]:
arr9 = np.ones((6,6))
arr9[1:-1,1:-1] = 0
print(arr9)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


## 21. 
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

Replace the value 5 to 12

## 22. 
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Convert all the values of 1st array to 64

In [29]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
arr3d[0] = 64

In [31]:
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## 23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it


In [32]:
arr2d_x = np.random.randint(9, size=(3,4))
arr2d_x

array([[2, 5, 6, 7],
       [5, 8, 8, 6],
       [2, 0, 4, 1]])

In [33]:
arr2d_x[0]

array([2, 5, 6, 7])

## 24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it


In [34]:
arr2d_y = z = np.random.randint(9, size=(4,3))
arr2d_y

array([[1, 0, 0],
       [6, 2, 4],
       [1, 2, 8],
       [1, 6, 7]])

In [35]:
arr2d_y[1][1]

2

## 25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows


In [36]:
arr2d_z = z = np.random.randint(9, size=(4,3))
arr2d_z

array([[4, 4, 8],
       [3, 0, 3],
       [7, 3, 8],
       [8, 0, 6]])

In [37]:
arr2d_z[0:2,[-1]]


array([[8],
       [3]])

## 26. Create a 10x10 array with random values and find the minimum and maximum values


In [38]:
arr1_a =np.random.rand(10,10)
arr1_a

array([[0.24502255, 0.91505121, 0.52341609, 0.14045854, 0.18558286,
        0.48175553, 0.05697705, 0.26096036, 0.54330393, 0.70465848],
       [0.03931282, 0.95368925, 0.29630519, 0.3061977 , 0.12274309,
        0.9802278 , 0.43055866, 0.37645458, 0.83302692, 0.50347241],
       [0.02416657, 0.62019929, 0.64433489, 0.99676713, 0.28365237,
        0.42911642, 0.56229046, 0.54883672, 0.18844689, 0.06903551],
       [0.00446879, 0.38088356, 0.08186786, 0.08485994, 0.05739496,
        0.49521756, 0.77414662, 0.83190943, 0.63298888, 0.50158132],
       [0.37393223, 0.66941749, 0.5912463 , 0.02021105, 0.96359881,
        0.93964742, 0.93922898, 0.99203132, 0.05337239, 0.51968709],
       [0.24695812, 0.22540465, 0.18374099, 0.41905045, 0.97535792,
        0.21170045, 0.22383655, 0.45367035, 0.87860586, 0.94499348],
       [0.80852835, 0.07688234, 0.49190473, 0.71553839, 0.60169251,
        0.43648987, 0.96386558, 0.45016831, 0.73888673, 0.23346414],
       [0.05672681, 0.60106803, 0.6522122

In [39]:
min_val = np.amin(arr1_a)
max_val = np.amax(arr1_a)

In [40]:
print(f"Minimum Value is: {min_val}")
print(f"Maximun Value is: {max_val}")

Minimum Value is: 0.00446878760599978
Maximun Value is: 0.9967671308269617


## 27.
a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

Find the common items between a and b

In [41]:
abc = np.array([1,2,3,2,3,4,3,4,5,6])
xyz = np.array([7,2,10,2,7,4,9,4,9,8])

In [42]:
np.intersect1d(abc, xyz)

array([2, 4])

## 28. 
a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

Find the positions where elements of a and b match

In [43]:
abc = np.array([1,2,3,2,3,4,3,4,5,6])
xyz = np.array([7,2,10,2,7,4,9,4,9,8])

In [44]:
aa = np.in1d(abc, xyz)
np.where(aa == True,"Match","Not matched")

array(['Not matched', 'Match', 'Not matched', 'Match', 'Not matched',
       'Match', 'Not matched', 'Match', 'Not matched', 'Not matched'],
      dtype='<U11')

## 29. 
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 

data = np.random.randn(7, 4)

Find all the values from array data where the values from array names are not equal to Will

In [45]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [46]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [47]:
data

array([[-0.30074247, -0.62167427,  0.30528549,  0.4397331 ],
       [-0.84508126,  0.38448128,  1.10149425, -0.94304434],
       [-1.60779854,  1.15414123,  0.6000453 , -2.14476639],
       [ 1.50342866,  1.25998712, -0.83054109, -0.59708332],
       [ 2.76877419, -0.40512838, -0.80824232, -0.1972378 ],
       [ 1.49125803, -1.11438527, -0.06064021,  0.97812474],
       [-0.3113854 , -0.42754477,  0.96689958,  0.47454   ]])

In [48]:
print(data[names != 'Will'])

[[-0.30074247 -0.62167427  0.30528549  0.4397331 ]
 [-0.84508126  0.38448128  1.10149425 -0.94304434]
 [ 1.50342866  1.25998712 -0.83054109 -0.59708332]
 [ 1.49125803 -1.11438527 -0.06064021  0.97812474]
 [-0.3113854  -0.42754477  0.96689958  0.47454   ]]


## 30. 
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

Find all the values from array data where the values from array names are not equal to Will and Joe

In [49]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data

array([[ 2.2280523 , -0.27630503, -0.21199044, -0.18667196],
       [-1.32612241, -1.48665857,  0.11633353,  0.85310713],
       [ 0.98247028, -0.03153621, -0.43387697, -0.64787561],
       [-0.05256236,  0.60316898,  0.09564721, -1.0539714 ],
       [ 0.98312558, -0.14619871, -1.01420924, -0.50958633],
       [-0.55516912, -0.14071825, -0.11061844,  1.28695182],
       [ 0.39401626,  0.16390888,  0.03330409, -0.51008302]])

In [50]:
print(data[(names != 'Will') & (names != 'Joe')])

[[ 2.2280523  -0.27630503 -0.21199044 -0.18667196]
 [-0.05256236  0.60316898  0.09564721 -1.0539714 ]]


## 31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.


In [51]:
arr1_2d = np.arange(1,16,dtype='float')
arr1_2d
arr1_2d.reshape(5,3)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

## 32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.


In [52]:
arr_s = np.arange(1,17,dtype='float')
arr_s
arr_s_new = arr_s.reshape(2,2,4)
arr_s_new

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

## 33. Swap axes of the array you created in Question 32


In [53]:
arr_s_new
np.swapaxes(arr_s_new,1,2)

array([[[ 1.,  5.],
        [ 2.,  6.],
        [ 3.,  7.],
        [ 4.,  8.]],

       [[ 9., 13.],
        [10., 14.],
        [11., 15.],
        [12., 16.]]])

## 34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0


In [54]:
arr10 = np.random.randn(10)
print(arr10)


[ 1.48377949  0.15528853  3.37253236 -0.02888316  0.2021331  -0.49178072
  1.73218648 -0.57711826 -0.25482716 -1.14065964]


In [55]:
x = 0
for i in arr10:
    if i<0.5:
        arr10[x] = 0
    x = x+1
print(arr10)

[1.48377949 0.         3.37253236 0.         0.         0.
 1.73218648 0.         0.         0.        ]


In [56]:
np.sqrt(arr10)

array([1.21810488, 0.        , 1.83644558, 0.        , 0.        ,
       0.        , 1.31612556, 0.        , 0.        , 0.        ])

## 35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays


In [74]:
arr11 = np.random.randn(12)
arr12 = np.random.randn(12)
print(arr11)
print(arr12)
print("\nMaximum values between both arrays are as folow\n",np.maximum(arr11,arr12))


[ 0.12136091  0.80108275 -0.44145842  1.25780196 -1.4156469   0.54902131
 -0.16624259  0.81518135  0.56093804 -0.97584059  0.33408139  0.5052081 ]
[ 0.16749388 -1.24306588 -0.13952054  0.54561578 -1.39561453 -2.10763889
 -0.95817931  0.02998378  1.57104285 -0.47871138  1.51717057 -0.69320473]

Maximum values between both arrays are as folow
 [ 0.16749388  0.80108275 -0.13952054  1.25780196 -1.39561453  0.54902131
 -0.16624259  0.81518135  1.57104285 -0.47871138  1.51717057  0.5052081 ]


## 36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])    Find the unique names and sort them out!

In [75]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

## 37. 
a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])

From array a remove all items present in array b

In [57]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
r = np.setdiff1d(a,b)
print(r)

[1 2 3 4]


## 38. 
Following is the input NumPy array delete column two and insert following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])

In [78]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [89]:
newColumn = np.array([[10,10,10]])
sampleArray[:,1] = newColumn
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

## 39. 
x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])

Find the dot product of the above two matrix

In [58]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

## 40. Generate a matrix of 20 random values and find its cumulative sum


In [59]:
arr_l = np.random.randn(20)
arr_l

array([ 0.19572285, -0.97811556,  0.6192547 , -0.58020945, -0.22988155,
       -0.68359752,  0.26711604, -1.39657573, -0.27352661, -2.24269826,
        0.64679933, -0.29717541, -0.7408946 ,  1.85563939, -0.56309825,
        2.63146463, -0.798928  ,  2.32215047,  0.82827033,  1.01283148])

In [60]:
np.cumsum(arr_l)

array([ 0.19572285, -0.78239271, -0.16313801, -0.74334746, -0.97322901,
       -1.65682653, -1.38971049, -2.78628622, -3.05981283, -5.3025111 ,
       -4.65571177, -4.95288717, -5.69378177, -3.83814238, -4.40124063,
       -1.76977601, -2.56870401, -0.24655354,  0.5817168 ,  1.59454828])